import type { LearningModule } from "./types.ts";

export const modules: LearningModule[] = [
  {
    id: 1,
    level: "AI 101",
    slug: "learning-problem",
    title: "A learning problem is a contract",
    shortTitle: "The learning contract",
    question: "What exactly is a model learning, and what does success mean?",
    summary: "Separate examples, features, targets, hypotheses, loss, data splits, and deployment distribution before judging a model.",
    status: "established",
    duration: 24,
    prerequisites: [],
    objectives: ["Write a supervised learning problem as data, model, and loss", "Explain why a held-out test set estimates a conditional quantity", "Detect distribution shift hidden by a single accuracy number"],
    analogy: {
      useful: "A learning problem is like writing an exam and its marking scheme before teaching the class.",
      boundary: "Unlike a classroom exam, deployment examples may come from a different population, and the metric can reward behavior nobody intended.",
    },
    formal: {
      notation: "D_train={(x_i,y_i)}; f_θ:x↦ŷ; θ*=argmin_θ (1/n)Σℓ(f_θ(x_i),y_i)",
      explanation: "Training selects parameters using empirical loss. Validation chooses among decisions. A test set estimates performance only for the sampled protocol and distribution; it does not certify all future use.",
    },
    workedExample: {
      prompt: "A classifier gets 95 of 100 examples right, but 90 examples belong to one easy class.",
      steps: ["Accuracy = 95/100 = 0.95.", "If all 10 minority examples are wrong, minority recall is 0/10 = 0.", "The aggregate metric hides total failure on the minority class."],
      answer: "Report the confusion matrix and per-class metrics; 95% accuracy alone is not an adequate success contract.",
    },
    misconceptions: ["Training loss is not deployment quality.", "A random split does not protect against temporal, geographic, or user shift."],
    lab: { kind: "benchmark", title: "Metric lens", instruction: "Change class balance and compare accuracy with balanced accuracy." },
    retrieval: ["What are the separate jobs of train, validation, and test data?", "When can test accuracy be an optimistic estimate?", "Name one metric that can hide a safety-relevant subgroup failure."],
    researchLimit: "Reliable evaluation under changing, strategic, or underspecified deployment conditions remains an open systems problem.",
    sourceIds: ["bishop-prml", "stanford-cs229", "helm"],
  },
  {
    id: 2,
    level: "AI 101",
    slug: "math-for-learning",
    title: "The mathematical objects under the metaphors",
    shortTitle: "Math for learning",
    question: "Which pieces of math actually explain learning algorithms?",
    summary: "Vectors locate observations, probability expresses uncertainty, derivatives describe local change, and information quantifies distinguishability.",
    status: "established",
    duration: 32,
    prerequisites: ["learning-problem"],
    objectives: ["Interpret a vector and dot product geometrically", "Distinguish probability from model confidence", "Use a derivative to predict a small loss change"],
    analogy: { useful: "A derivative is a local slope signpost: it says which nearby direction rises fastest.", boundary: "A local signpost does not reveal distant cliffs, saddle points, flat regions, or whether the map itself is wrong." },
    formal: { notation: "p(y|x); x·w=Σ_j x_jw_j; ∇_θL=[∂L/∂θ_1,…]; H(p)=-Σp log p", explanation: "These are different objects: a conditional distribution, an inner product, a vector of local partial derivatives, and entropy. Neural-network training composes them rather than replacing them with one mystical operation." },
    workedExample: { prompt: "For p=(0.5,0.5), compute entropy in bits.", steps: ["H=-[0.5 log₂0.5+0.5 log₂0.5].", "Each log₂0.5=-1.", "H=1 bit."], answer: "The balanced binary distribution has 1 bit of entropy; p=(1,0) has 0." },
    misconceptions: ["A probability is conditional on a model and evidence, not a truth meter.", "A gradient points uphill; gradient descent moves in the negative-gradient direction."],
    lab: { kind: "geometry", title: "Vector field desk", instruction: "Move two vectors and compare angle, dot product, and cosine similarity." },
    retrieval: ["Why can two vectors have a large dot product but modest cosine similarity?", "What does entropy measure?", "What information does a first derivative omit?"],
    researchLimit: "High-dimensional geometry often defeats low-dimensional intuition; visualizations are projections, not windows into a literal latent world.",
    sourceIds: ["bishop-prml", "hamming-art", "welch-ai"],
  },
  {
    id: 3,
    level: "AI 101",
    slug: "learning-signals",
    title: "Learning paradigms differ by where the signal comes from",
    shortTitle: "Learning signals",
    question: "Are supervised, self-supervised, imitation, and reinforcement learning separate engines?",
    summary: "Classify methods by the data-generating process and training signal, not by a ladder from primitive to intelligent.",
    status: "established",
    duration: 28,
    prerequisites: ["learning-problem"],
    objectives: ["Identify the target source in six learning setups", "Explain why self-supervision can be autoregressive or contrastive", "Separate behavior cloning from reward-driven learning"],
    analogy: { useful: "Different paradigms are different feedback channels: answer key, hidden-piece puzzle, demonstration, or consequence.", boundary: "Real systems mix channels. A model architecture is not permanently married to one channel." },
    formal: { notation: "supervised: ℓ(f(x),y); SSL: ℓ(g(c(x)),t(x)); imitation: -logπ(a|s); RL: E_π[Σγ^t r_t]", explanation: "The objective reveals the signal. In SSL, target t(x) is constructed from the sample, but it need not be an uncorrupted original: next-token prediction and contrastive pairing are counterexamples." },
    workedExample: { prompt: "A model predicts the next token from previous tokens in raw text.", steps: ["No human label is added per sequence.", "The observed next token supplies the target.", "The objective is autoregressive cross-entropy, not denoising a corrupted input."], answer: "This is self-supervised autoregressive learning." },
    misconceptions: ["Self-supervised does not mean label-free in the sense of having no targets.", "RL is not any loop with feedback, and inference-time sampling is not automatically RL."],
    lab: { kind: "search", title: "Signal sorter", instruction: "Classify scenarios by target source, then reveal mixed cases." },
    retrieval: ["Why is next-token prediction self-supervised?", "What distinguishes imitation learning from RL?", "Give a mixed training pipeline."],
    researchLimit: "Terminology varies across subfields, so papers should be read through their objective and data pipeline rather than their marketing label.",
    sourceIds: ["bert", "simclr", "dqn", "instructgpt"],
  },
  {
    id: 4,
    level: "AI 101",
    slug: "classical-models",
    title: "Simple models expose the real tradeoffs",
    shortTitle: "Classical models",
    question: "Why learn linear models, trees, and nearest neighbors in the age of foundation models?",
    summary: "Simple models make inductive bias, calibration, bias-variance tradeoffs, and failure analysis visible.",
    status: "established",
    duration: 30,
    prerequisites: ["math-for-learning"],
    objectives: ["Interpret a linear decision boundary", "Compare parametric and instance-based prediction", "Separate discrimination from calibration"],
    analogy: { useful: "A model is a ruler cut to a particular shape: straight rulers measure straight relations cheaply.", boundary: "More flexible rulers can fit noise, and a familiar shape does not guarantee the data-generating process shares it." },
    formal: { notation: "p(y=1|x)=σ(wᵀx+b); kNN(x)=mode{y_i:i∈N_k(x)}", explanation: "Logistic regression learns a linear log-odds surface; k-nearest neighbors defers much of the work to query time. Their errors differ even on the same representation." },
    workedExample: { prompt: "With logit z=ln 3, what probability does logistic regression assign?", steps: ["σ(z)=1/(1+e^{-z}).", "e^{-ln3}=1/3.", "σ=1/(4/3)=0.75."], answer: "The model assigns 75%, which can still be miscalibrated across repeated cases." },
    misconceptions: ["A calibrated 70% prediction is not the same as a correct prediction.", "Low training error does not imply low bias or low variance on new data."],
    lab: { kind: "gradient", title: "Boundary workshop", instruction: "Move points and compare a linear separator with nearest-neighbor regions." },
    retrieval: ["What makes kNN instance-based?", "Can an accurate model be miscalibrated?", "How does regularization change a linear model's bias and variance?"],
    researchLimit: "Simple baselines remain essential because gains from complex models can vanish under a shifted or cost-sensitive protocol.",
    sourceIds: ["bishop-prml", "mit-ml-intro", "stanford-cs229"],
  },
  {
    id: 5,
    level: "AI 101",
    slug: "neural-learning",
    title: "Neural networks learn by composing functions",
    shortTitle: "Neural learning",
    question: "What does backpropagation do, and what does it not do?",
    summary: "Architecture defines a function family; the objective scores behavior; backprop computes derivatives; the optimizer chooses an update.",
    status: "established",
    duration: 36,
    prerequisites: ["math-for-learning", "classical-models"],
    objectives: ["Trace a two-layer forward pass", "Use the chain rule to attribute a loss derivative", "Keep architecture, objective, data, and optimizer distinct"],
    analogy: { useful: "Backprop is an accounting pass that assigns each adjustable part its share of a local error change.", boundary: "It does not understand the error, choose the goal, guarantee a global optimum, or explain the model's concept." },
    formal: { notation: "h=φ(W₁x+b₁); ŷ=W₂h+b₂; ∂L/∂W₁=(∂L/∂ŷ)(∂ŷ/∂h)(∂h/∂W₁)", explanation: "Reverse-mode automatic differentiation reuses intermediate derivatives through the computation graph. Gradient descent then applies θ←θ-η∇L; those are separate operations." },
    workedExample: { prompt: "For ŷ=wx, L=(ŷ-y)², x=2, y=5, w=0, take η=0.1.", steps: ["∂L/∂w=2(wx-y)x=2(-5)(2)=-20.", "w'=0-0.1(-20)=2.", "New prediction is 4; squared error falls from 25 to 1."], answer: "One verified step sharply reduces this example's loss, but a larger step could overshoot." },
    misconceptions: ["Backpropagation is derivative computation, not the optimizer itself.", "A loss decrease on one batch does not prove generalization."],
    lab: { kind: "gradient", title: "One honest gradient step", instruction: "Change the point and learning rate; observe descent, overshoot, and divergence." },
    retrieval: ["Which object chooses the update direction?", "Why can a learning rate be too large?", "What role does a nonlinear activation play?"],
    researchLimit: "Optimization behavior in large networks is partly understood empirically; clean low-dimensional landscapes are teaching devices, not faithful replicas.",
    sourceIds: ["bishop-prml", "welch-ai", "stanford-cs229"],
  },
  {
    id: 6,
    level: "AI 201",
    slug: "representations",
    title: "A representation is a coordinate system learned for a job",
    shortTitle: "Representations",
    question: "Is a latent space a circle containing everything the model knows?",
    summary: "Embeddings encode task-useful relations under a chosen objective; their geometry is distributed, non-identifiable, and only partially observable.",
    status: "active-program",
    asOf: "2026-08-15",
    duration: 34,
    prerequisites: ["neural-learning"],
    objectives: ["Compute and critique cosine similarity", "Explain non-identifiability under rotations", "Use the circle analogy without treating it as a hard boundary"],
    analogy: { useful: "The circle is useful as a reminder that experience constrains a learner's starting distribution.", boundary: "There is no single known rim. Knowledge is not stored as points on one 2-D disk; parameters, activations, context, tools, and environment all affect reachable behavior." },
    formal: { notation: "z=f_θ(x)∈R^d; sim(z_i,z_j)=z_iᵀz_j/(||z_i||||z_j||)", explanation: "A representation maps inputs to coordinates. Distances become meaningful only relative to the objective, normalization, layer, probe, and invariances. If every vector is rotated by the same orthogonal matrix, dot products stay unchanged." },
    workedExample: { prompt: "Compare a=(1,0), b=(3,0), and c=(0,2).", steps: ["cos(a,b)=3/(1·3)=1.", "cos(a,c)=0/(1·2)=0.", "Magnitude differs, yet a and b have identical direction."], answer: "Cosine captures angle, not norm or truth; its interpretation depends on how the representation was trained." },
    misconceptions: ["A latent space is not a literal fact database.", "Interpolation and extrapolation are not separated by a visible universal boundary."],
    lab: { kind: "geometry", title: "Rotating atlas", instruction: "Rotate and rescale embeddings; watch which geometric claims survive." },
    retrieval: ["Why are latent axes often non-identifiable?", "What does cosine similarity ignore?", "Where does the circle analogy stop working?"],
    researchLimit: "Connecting learned coordinates to stable, causal, human-interpretable factors remains unsettled.",
    sourceIds: ["bishop-prml", "ijepa", "causal-rep"],
  },
  {
    id: 7,
    level: "AI 201",
    slug: "self-supervision",
    title: "Self-supervision is a family of prediction games",
    shortTitle: "Self-supervision",
    question: "Is every modern model trained by corrupting data and reconstructing the clean original?",
    summary: "Masked reconstruction is one member of a larger family that includes autoregressive, contrastive, clustering, and joint-embedding objectives.",
    status: "established",
    duration: 32,
    prerequisites: ["learning-signals", "representations"],
    objectives: ["Distinguish five SSL objectives", "Identify shortcut opportunities", "Explain why data quality still matters without human labels"],
    analogy: { useful: "SSL is a teacher who manufactures questions from the material itself.", boundary: "The manufactured answer need not be the original clean sample, and the chosen question controls which regularities are rewarded." },
    formal: { notation: "AR: -Σ_t log p(x_t|x_<t); masked: ℓ(g(c(x)),x_mask); contrastive: -log exp(sim(z,z⁺)/τ)/Σ_j exp(sim(z,z_j)/τ)", explanation: "All create targets from observed structure, but they impose different invariances and information bottlenecks. The objective, augmentation, and sampling distribution determine what counts as a shortcut." },
    workedExample: { prompt: "Which objective uses two augmented views as a positive pair and other images as negatives?", steps: ["No pixels are reconstructed.", "Similarity of the paired representations is raised.", "Similarity to other batch examples appears in the denominator."], answer: "A contrastive objective such as SimCLR, not a denoising autoencoder." },
    misconceptions: ["Unlabeled does not mean uncurated or harmless.", "V-JEPA is self-supervised, not a third paradigm replacing SSL."],
    lab: { kind: "geometry", title: "Objective switchboard", instruction: "Switch objectives and inspect what information each target preserves." },
    retrieval: ["Give a self-supervised objective with no corruption step.", "How can augmentation create a shortcut?", "Why does web data quality still affect SSL?"],
    researchLimit: "No single pretext task guarantees the abstractions needed for every downstream task or causal environment.",
    sourceIds: ["bert", "simclr", "mae", "ijepa", "vjepa"],
  },
  {
    id: 8,
    level: "AI 201",
    slug: "generative-families",
    title: "Generative models take different roads to a distribution",
    shortTitle: "Generative families",
    question: "Are VAEs, GANs, diffusion, and flow matching versions of the same denoising loop?",
    summary: "They share the aim of modeling data distributions but differ in objective, latent path, likelihood treatment, and sampling dynamics.",
    status: "established",
    duration: 38,
    prerequisites: ["representations", "self-supervision"],
    objectives: ["State the training signal for four generative families", "Compare sampling cost and objective", "Avoid equating generation with novelty"],
    analogy: { useful: "Each family learns a route from a simple source to a complicated data distribution.", boundary: "A transport route is not a semantic explanation, and visually plausible samples can still be memorized, biased, or physically wrong." },
    formal: { notation: "VAE: E_q[log p(x|z)]-KL(q(z|x)||p(z)); GAN: min_G max_D E logD(x)+E log(1-D(G(z))); flow: dx_t/dt=v_θ(x_t,t)", explanation: "VAEs optimize a variational bound, GANs play an adversarial distribution game, diffusion learns reverse corruption dynamics, and flow matching regresses a vector field along chosen probability paths." },
    workedExample: { prompt: "A two-step sampler applies x₁=x₂-ε₂ and x₀=x₁-ε₁.", steps: ["The final output is x₀=x₂-(ε₂+ε₁).", "An error at either step changes the sample.", "More steps can refine a path but add latency."], answer: "Iterative generation accumulates model and numerical choices; 'denoising' does not mean recovering one stored original." },
    misconceptions: ["Diffusion sampling is not restoring the exact training image that was corrupted.", "A GAN's discriminator is not a universal truth verifier."],
    lab: { kind: "gradient", title: "Distribution routes", instruction: "Compare adversarial, noisy, and continuous transport paths on the same toy mixture." },
    retrieval: ["What does the KL term do in a VAE?", "Why can GAN training be unstable?", "How does flow matching differ from simulating a diffusion SDE during training?"],
    researchLimit: "Likelihood, perceptual fidelity, controllability, and physical consistency remain different objectives with no universal scalar ranking.",
    sourceIds: ["vae", "gan", "ddpm", "flow-matching"],
  },
  {
    id: 9,
    level: "AI 201",
    slug: "generalization",
    title: "Generalization is a measured relation, not an escape radius",
    shortTitle: "Generalization",
    question: "Can a model only remix points inside its training-data circle?",
    summary: "Generalization ranges from familiar interpolation to systematic composition and distribution shift; the label depends on representation and protocol.",
    status: "active-program",
    asOf: "2026-08-15",
    duration: 34,
    prerequisites: ["learning-problem", "representations"],
    objectives: ["Define in- and out-of-distribution relative to a protocol", "Separate memorization from recombination", "Design a test for one claimed extrapolation"],
    analogy: { useful: "The circle warns that evidence supports some neighborhoods better than others.", boundary: "High-dimensional support is sparse and folded; a point can be geometrically nearby yet causally novel, or far in pixels but semantically routine." },
    formal: { notation: "R_P(f)=E_(x,y)~P[ℓ(f(x),y)]; shift asks about R_Q(f), Q≠P", explanation: "Generalization is always relative to train distribution P, evaluation distribution Q, task, representation, and metric. There is no theorem that next-token training forbids all novel deductions, nor one that fluent recombination proves open-ended discovery." },
    workedExample: { prompt: "Train on x∈[-1,1] for y=2x, then test x=1.5.", steps: ["1.5 is outside the sampled input interval.", "The correct linear rule predicts 3.", "A flexible model may or may not learn that rule."], answer: "This is extrapolation in raw x, but its difficulty depends on learned inductive bias; 'outside' alone does not determine failure." },
    misconceptions: ["Novel output is not evidence of novel knowledge.", "Out-of-distribution is not one fixed property of an example."],
    lab: { kind: "gradient", title: "Boundary without a circle", instruction: "Change the training interval and model family; compare interpolation and extrapolation errors." },
    retrieval: ["Why must OOD name a reference distribution?", "Can a linear model extrapolate?", "What evidence distinguishes memorization from composition?"],
    researchLimit: "Robust compositional and causal generalization across uncontrolled shifts remains a central unsolved problem.",
    sourceIds: ["bishop-prml", "gpt3", "emergence-mirage"],
  },
  {
    id: 10,
    level: "AI 201",
    slug: "reinforcement-learning",
    title: "Reinforcement learning optimizes behavior through consequences",
    shortTitle: "RL foundations",
    question: "If failure is cheap, can RL search forever and keep discovering?",
    summary: "RL couples an agent, environment, actions, observations, and rewards; compute cannot remove reward misspecification, partial observability, or combinatorial growth.",
    status: "established",
    duration: 42,
    prerequisites: ["learning-signals", "generalization"],
    objectives: ["Write an MDP and discounted return", "Distinguish model-free, model-based, on-policy, off-policy, and offline RL", "Explain why reward is evidence about an objective, not truth"],
    analogy: { useful: "The food-seeking child captures adaptation from consequences and the possibility of revising a bad starting belief.", boundary: "Human learning mixes language, social imitation, memory, curiosity, embodiment, and goals. 'Food reward' is not a complete reward function or a faithful brain model." },
    formal: { notation: "M=(S,A,P,R,γ); J(π)=E_π[Σ_t γ^t r_t]; V^π(s)=E_π[G_t|s_t=s]", explanation: "A policy selects actions. The transition process returns new states and rewards. A value estimates expected future return under a policy; it is learned from interaction or data, not a graph-search heuristic by definition." },
    workedExample: { prompt: "Rewards are [0,0,10] with γ=0.5.", steps: ["G₀=0+0.5·0+0.5²·10.", "0.5²=0.25.", "G₀=2.5."], answer: "The distant reward contributes 2.5 now; discounting changes which paths the agent prefers." },
    misconceptions: ["RL is not A*, BFS, or DFS, though planning can use search inside an RL system.", "More trials do not fix a misspecified or gameable reward."],
    lab: { kind: "return", title: "Return telescope", instruction: "Change reward timing and γ; inspect when a longer path becomes preferable." },
    retrieval: ["What makes a process Markov?", "Why can offline RL overestimate unseen actions?", "How can a high reward accompany unwanted behavior?"],
    researchLimit: "Safe exploration, long-horizon credit, distribution shift, and reward specification still prevent 'infinite scale' from becoming infinite reliable discovery.",
    sourceIds: ["dqn", "ppo", "cql", "dreamer", "reward-tampering"],
  },
  {
    id: 11,
    level: "AI 301",
    slug: "transformers",
    title: "A transformer routes information through context",
    shortTitle: "Transformers",
    question: "What happens between a token and the next-token distribution?",
    summary: "Token embeddings, position information, attention, residual mixing, and feed-forward transformations build context-dependent activations.",
    status: "established",
    duration: 40,
    prerequisites: ["neural-learning", "representations", "self-supervision"],
    objectives: ["Compute two-token scaled dot-product attention", "Separate parameters from activations", "Explain causal next-token training without calling it denoising"],
    analogy: { useful: "Attention is a content-addressed routing table: each position requests a weighted mixture of available value vectors.", boundary: "A weight is not an explanation, memory address, probability of truth, or proof that one token caused the output." },
    formal: { notation: "Attention(Q,K,V)=softmax(QKᵀ/√d_k)V; h_{l+1}=h_l+F_l(h_l)", explanation: "Queries score keys; softmax normalizes scores; values are mixed. Residual streams preserve and update information across layers. Causal masks prevent access to future tokens during autoregressive training." },
    workedExample: { prompt: "One query scores two keys as [1,0] with d_k=1.", steps: ["softmax([1,0])=[e/(e+1),1/(e+1)].", "Numerically this is about [0.731,0.269].", "The output is that weighted mixture of the two value vectors."], answer: "The higher-scored key contributes more, but both values contribute." },
    misconceptions: ["Attention weights alone are not faithful feature attributions.", "Next-token prediction hides the target from the prefix but need not corrupt the prefix."],
    lab: { kind: "attention", title: "Attention workbench", instruction: "Edit query-key alignment and watch normalized weights and value mixtures update." },
    retrieval: ["Why divide logits by √d_k?", "What is mixed: keys or values?", "What does a causal mask prohibit?"],
    researchLimit: "Mechanistic accounts explain selected circuits and behaviors, not a complete causal theory of large-model computation.",
    sourceIds: ["attention", "rope", "induction-heads", "welch-ai"],
  },
  {
    id: 12,
    level: "AI 301",
    slug: "compute-and-context",
    title: "Model size, context, and runtime memory are different budgets",
    shortTitle: "Compute and context",
    question: "What do parameters, activations, KV cache, quantization, and experts each buy?",
    summary: "Account for storage, training FLOPs, active parameters, memory traffic, and context position separately.",
    status: "active-program",
    asOf: "2026-08-15",
    duration: 34,
    prerequisites: ["transformers"],
    objectives: ["Estimate raw parameter memory", "Explain why total and active expert parameters differ", "Distinguish context capacity from context utilization"],
    analogy: { useful: "Parameters are a learned program, activations its temporary workspace, and KV cache a context-specific notebook.", boundary: "Neural parameters are not readable instructions, and a larger notebook does not guarantee the model notices a fact in its middle pages." },
    formal: { notation: "weight memory≈N_params·bits/8; attention score matrix O(n²); KV cache grows O(n·L·d)", explanation: "Quantization reduces bits per stored value with accuracy tradeoffs. Sparse experts activate subsets of a larger parameter pool. IO-aware kernels can make exact attention faster without changing its mathematical result." },
    workedExample: { prompt: "How much raw storage do 8 billion 4-bit weights require?", steps: ["4 bits = 0.5 bytes.", "8×10⁹·0.5=4×10⁹ bytes.", "That is about 4 GB decimal before scales, metadata, cache, and activations."], answer: "About 4 GB for raw weights, not total runtime memory." },
    misconceptions: ["A 1M-token context window is not 1M tokens of equally reliable memory.", "Total MoE parameters do not equal per-token active compute."],
    lab: { kind: "attention", title: "Runtime accountant", instruction: "Vary precision, sequence length, layers, and active experts to compare budgets." },
    retrieval: ["Why is KV cache input-dependent?", "What does quantization trade?", "How can an exact kernel be faster without approximating attention?"],
    researchLimit: "Reported context limits, throughput, and memory use depend strongly on hardware, batching, kernels, and evaluation positions.",
    sourceIds: ["lost-middle", "switch", "flashattention", "lora"],
  },
  {
    id: 13,
    level: "AI 301",
    slug: "scaling-laws",
    title: "Scaling curves describe regimes; they do not promise infinity",
    shortTitle: "Scaling laws",
    question: "Is the datacenter race evidence that more compute can keep producing intelligence indefinitely?",
    summary: "Empirical power laws guide allocation inside observed regimes; data, objectives, inference, economics, and evaluation determine what the curve means.",
    status: "active-program",
    asOf: "2026-08-15",
    duration: 35,
    prerequisites: ["learning-problem", "compute-and-context"],
    objectives: ["Read a log-log power law", "Explain compute-optimal allocation", "Name three reasons a smooth loss curve need not mean smooth capability"],
    analogy: { useful: "A scaling law is a fitted road gradient over surveyed terrain.", boundary: "It is not a physical law that the road continues forever, reaches intelligence, or offers the same economic return." },
    formal: { notation: "L(N,D,C)≈L_∞+aN^{-α}+bD^{-β}; C≈kND", explanation: "The fitted exponents summarize held-out loss under a model family, data regime, and compute accounting. Capability metrics can be discontinuous, contaminated, saturated, or economically irrelevant even when loss improves." },
    workedExample: { prompt: "If reducible loss follows aC^{-0.1}, what does 10× compute do?", steps: ["Ratio=(10C)^{-0.1}/C^{-0.1}=10^{-0.1}.", "10^{-0.1}≈0.794.", "Reducible loss falls by about 20.6%, not 10×."], answer: "Power laws imply diminishing marginal improvement for a fixed exponent." },
    misconceptions: ["Scaling laws are empirical fits, not an intelligence conservation law.", "Current infrastructure investment has training, inference, reliability, market, and strategic drivers—not only RL search."],
    lab: { kind: "benchmark", title: "Log-log observatory", instruction: "Change exponent, irreducible loss, and budget; inspect extrapolation sensitivity." },
    retrieval: ["What assumptions hide inside a compute-optimal recommendation?", "Why can a thresholded metric look emergent?", "What does irreducible loss represent in a fit?"],
    researchLimit: "The transfer of historical scaling fits to new architectures, synthetic data, inference-time compute, and real economic value is not guaranteed.",
    sourceIds: ["scaling-laws", "chinchilla", "emergence-mirage", "hamming-art"],
  },
  {
    id: 14,
    level: "AI 301",
    slug: "post-training",
    title: "Post-training reshapes behavior without replacing pretraining",
    shortTitle: "Post-training",
    question: "What are SFT, RLHF, RLAIF, DPO, and RL with verifiable rewards actually doing?",
    summary: "Separate demonstrations, preferences, reward models, policy optimization, direct preference objectives, verifiers, rejection sampling, and distillation.",
    status: "frontier-snapshot",
    asOf: "2026-08-15",
    duration: 40,
    prerequisites: ["reinforcement-learning", "transformers"],
    objectives: ["Trace the InstructGPT pipeline", "Compare PPO-style RLHF with DPO", "Distinguish verifiable reward from universal correctness"],
    analogy: { useful: "Pretraining supplies a broad repertoire; post-training changes which behaviors are selected and reinforced.", boundary: "It is not a clean separation between knowledge and reasoning, and preference optimization can alter capabilities, calibration, and style in entangled ways." },
    formal: { notation: "SFT: -logπ(y|x); preference: P(y_w≻y_l)=σ(r(x,y_w)-r(x,y_l)); RL: max E[r-β KL(π||π_ref)]", explanation: "One pipeline fits demonstrations, learns a preference reward, then optimizes a policy with a KL constraint. DPO derives a direct classification-style objective under specific assumptions. Verifiable rewards replace some subjective labels only where checking is reliable." },
    workedExample: { prompt: "A reward model scores answer A=2 and B=0. What Bradley-Terry preference probability does it assign?", steps: ["Difference=2.", "P(A≻B)=σ(2).", "σ(2)≈0.881."], answer: "About 88.1%; this is model confidence in the preference relation, not proof A is true." },
    misconceptions: ["RLHF does not guarantee truth or safety.", "Constitutional AI is not an immutable constitution hardcoded as absolute logic in a loss."],
    lab: { kind: "return", title: "Preference pressure", instruction: "Change reward gaps and KL penalty; observe policy movement and collapse pressure." },
    retrieval: ["What is the role of the reference policy?", "How does DPO differ operationally from PPO-based RLHF?", "Where are verifiable rewards strongest?"],
    researchLimit: "Preference data and verifiers inherit coverage gaps; optimization can exploit those gaps or narrow behavior in hard-to-measure ways.",
    sourceIds: ["instructgpt", "constitutional-ai", "dpo", "process-supervision", "deepseek-r1"],
  },
  {
    id: 15,
    level: "AI 301",
    slug: "reasoning-and-search",
    title: "Generation, search, verification, and learning are separate axes",
    shortTitle: "Reasoning and search",
    question: "When a reasoning model branches, backtracks, or checks itself, is it running RL or MCTS?",
    summary: "Inference can sample, rank, vote, search, call tools, and verify without updating a policy; training-time RL is a separate mechanism.",
    status: "frontier-snapshot",
    asOf: "2026-08-15",
    duration: 42,
    prerequisites: ["post-training"],
    objectives: ["Distinguish decoding, search, and policy learning", "Compare outcome and process verification", "Reject undocumented claims about hidden proprietary reasoning loops"],
    analogy: { useful: "A generator proposes routes, a search controller allocates attempts, and a verifier checks candidates.", boundary: "Text that says 'wait, let me try again' does not prove a hidden tree, a value network, faithful introspection, or parameter learning." },
    formal: { notation: "best-of-N: argmax_{y_i~π} v(y_i); self-consistency: mode_i answer(y_i); RL update: θ←θ+η∇_θE[r]", explanation: "The first two spend inference compute under fixed parameters. RL changes a policy from reward-bearing experience. MCTS additionally requires explicit tree statistics and a selection/expansion/back-up procedure." },
    workedExample: { prompt: "Five sampled solutions give answers [7,7,9,7,9].", steps: ["Count answer 7: three.", "Count answer 9: two.", "Self-consistency returns 7."], answer: "Voting changed the selected answer without changing model parameters; it was inference-time aggregation, not online RL." },
    misconceptions: ["OpenAI o1 or DeepSeek-R1 should not be described as literal MCTS unless documented evidence says so.", "A value function is not identical to an A* heuristic."],
    lab: { kind: "search", title: "Search is not learning", instruction: "Compare BFS, heuristic search, best-of-N, and a policy update on one toy problem." },
    retrieval: ["What evidence would establish that a system uses MCTS?", "Can test-time compute be used without RL?", "When is verification easier than generation?"],
    researchLimit: "Hidden reasoning traces may be useful workspaces but are not guaranteed faithful causal explanations of the final answer.",
    sourceIds: ["self-consistency", "tree-thoughts", "process-supervision", "deepseek-r1", "alphageometry"],
  },
  {
    id: 16,
    level: "AI 301",
    slug: "multimodal-agents",
    title: "Grounding comes from interfaces and consequences, not modality count",
    shortTitle: "Multimodal agents",
    question: "Does one giant multimodal manifold let a model warp between fields and act in reality?",
    summary: "Cross-modal alignment, fusion, retrieval, tools, memory, and action loops add different information paths and failure modes.",
    status: "active-program",
    asOf: "2026-08-15",
    duration: 38,
    prerequisites: ["transformers", "representations"],
    objectives: ["Separate alignment from grounding", "Trace an observe-think-act tool loop", "Explain why analogy transfer is not a guaranteed scientific bridge"],
    analogy: { useful: "A shared embedding can place related text and images near one another, making translation across views easier.", boundary: "Nearness does not establish causal isomorphism. Cross-attention cannot 'warp' a correct quantum theory out of a biological analogy without evidence and validation." },
    formal: { notation: "z_x=f(x), z_t=g(t); CLIP: contrast paired (z_x,z_t); agent: o_t→π(a_t|h_t)→environment→o_{t+1}", explanation: "Multimodal objectives align chosen views. Agent scaffolds add history, tools, retrieval, and action protocols around a model. The external system can supply fresh evidence, but only through its sensors, APIs, permissions, and validation rules." },
    workedExample: { prompt: "A text-image model retrieves the correct picture 8 of 10 times but cannot control a robot arm.", steps: ["Retrieval shows alignment on this set.", "Control requires action outputs, temporal feedback, and embodiment data.", "No control conclusion follows from retrieval accuracy alone."], answer: "Multimodal alignment is useful but not sufficient for embodied competence." },
    misconceptions: ["More modalities do not make reality an unhackable verifier.", "A tool-using loop is not automatically autonomous, grounded, or safe."],
    lab: { kind: "search", title: "Agent anatomy", instruction: "Toggle memory, retrieval, tools, and feedback; observe which failures each component can address." },
    retrieval: ["What is the difference between alignment and grounding?", "Where can stale retrieval poison an agent?", "Why is cross-domain analogy only a hypothesis generator?"],
    researchLimit: "Agents compound model, tool, environment, state, security, and evaluation failures; benchmark success often transfers weakly to open environments.",
    sourceIds: ["clip", "react", "rt2", "open-x"],
  },
  {
    id: 17,
    level: "AI 401",
    slug: "world-models",
    title: "World model is a role, not one architecture",
    shortTitle: "World models",
    question: "Is JEPA the non-generative SOTA engine that replaced denoising for physical AI?",
    summary: "World models include latent dynamics for control, predictive representations, generative simulators, and language-space environment models.",
    status: "frontier-snapshot",
    asOf: "2026-08-15",
    duration: 40,
    prerequisites: ["generative-families", "reinforcement-learning", "multimodal-agents"],
    objectives: ["Classify four world-model roles", "Locate JEPA inside self-supervision", "Match a model claim to its evaluated task"],
    analogy: { useful: "A world model is an internal rehearsal space for predicting consequences before acting.", boundary: "Some world models predict features, some pixels, some rewards, and some text. 'Understanding physics' cannot be inferred from the label." },
    formal: { notation: "latent dynamics: z_{t+1}~p(z_{t+1}|z_t,a_t); observation: o_t~p(o_t|z_t); value: V(z_t)", explanation: "Control-oriented models compress histories into latent states and imagine action-conditioned futures. JEPAs instead define predictive representation objectives. These lines can be combined, but neither term specifies the whole system." },
    workedExample: { prompt: "A model predicts future video embeddings well but receives no actions.", steps: ["It learns temporal predictive structure.", "It does not model p(z_{t+1}|z_t,a_t) because a_t is absent.", "Control competence therefore remains untested."], answer: "It is a predictive representation model, not yet an action-conditioned control world model." },
    misconceptions: ["V-JEPA is SSL, not the opposite of SSL.", "JEPA is not the singular SOTA for all physical AI."],
    lab: { kind: "geometry", title: "World-model taxonomy", instruction: "Route systems by predicted object, action conditioning, rollout use, and evaluation." },
    retrieval: ["What makes a world model action-conditioned?", "How is JEPA trained?", "Why can pixel prediction still be useful for control?"],
    researchLimit: "Long-horizon counterfactual accuracy and planning utility can diverge sharply from short-horizon reconstruction or representation metrics.",
    sourceIds: ["dreamer", "ijepa", "vjepa", "diffusion-policy"],
  },
  {
    id: 18,
    level: "AI 401",
    slug: "embodied-ai",
    title: "Embodied intelligence lives in the closed loop",
    shortTitle: "Embodied AI",
    question: "What changes when prediction must survive contact with a robot and the world?",
    summary: "Behavior cloning, diffusion policies, VLAs, model-predictive control, proprioception, touch, sim-to-real, and recovery solve different loop segments.",
    status: "frontier-snapshot",
    asOf: "2026-08-15",
    duration: 44,
    prerequisites: ["world-models"],
    objectives: ["Trace perception-action feedback", "Compare cloning, diffusion policy, and model-based control", "Identify one sim-to-real and one recovery failure"],
    analogy: { useful: "Embodied learning is less like writing an answer and more like balancing while the exam paper moves.", boundary: "The real world supplies consequences, not clean labels; sensors alias state, hardware drifts, damage can be irreversible, and safety limits exploration." },
    formal: { notation: "history h_t=(o_{≤t},a_{<t}); policy a_t~π(a_t|h_t); MPC: argmax_{a_{t:t+H}}Σ r(ŝ_{t+k},a_{t+k})", explanation: "Closed-loop performance depends on state estimation, latency, policy, dynamics, actuators, and recovery. Diffusion policies model multimodal action sequences through denoising, directly contradicting the claim that denoising fails in physical control." },
    workedExample: { prompt: "A policy succeeds 18/20 times from training starts and 2/20 after small object shifts.", steps: ["Training-start success is 90%.", "Shifted-start success is 10%.", "Aggregate across both is 50%, but the condition split reveals brittle recovery."], answer: "Report intervention-conditioned results; the policy learned a narrow success basin." },
    misconceptions: ["Simulation is not a perfect physics verifier.", "A VLA's web knowledge does not guarantee precise contact dynamics."],
    lab: { kind: "return", title: "Closed-loop recovery", instruction: "Inject observation noise, action delay, and disturbances; compare open-loop and feedback policies." },
    retrieval: ["Why can behavior cloning compound error?", "How can a diffusion policy represent multiple valid actions?", "What does proprioception add?"],
    researchLimit: "Data coverage, contact-rich dynamics, hardware diversity, safe failure, and long-horizon recovery remain major barriers to general-purpose robotics.",
    sourceIds: ["diffusion-policy", "rt2", "open-x", "dreamer"],
  },
  {
    id: 19,
    level: "AI 401",
    slug: "evaluation-science",
    title: "A benchmark is an instrument with a calibration curve",
    shortTitle: "Evaluation science",
    question: "When can a benchmark justify the phrase state of the art?",
    summary: "SOTA must name task, data, protocol, metric, compute regime, cost, date, and uncertainty; rankings do not transfer automatically.",
    status: "active-program",
    asOf: "2026-08-15",
    duration: 38,
    prerequisites: ["learning-problem", "scaling-laws"],
    objectives: ["Write a scoped SOTA claim", "Compute pass@k under an independence assumption", "Audit contamination and ecological validity"],
    analogy: { useful: "A benchmark is a scientific instrument: it measures through a particular sensor and calibration.", boundary: "Unlike a passive thermometer, public benchmarks change behavior: developers tune to them, data leaks, and the measured population shifts." },
    formal: { notation: "pass@k≈1-(1-p)^k; confidence and cost must accompany score; SOTA=(task,data,protocol,metric,resources,date)", explanation: "Repeated sampling can raise success probability while multiplying compute. Pairwise ranking can reverse under different prompts, budgets, judges, or subgroups. A leaderboard is conditional evidence." },
    workedExample: { prompt: "A single independent sample succeeds with p=0.2. What is pass@5?", steps: ["Failure per sample=0.8.", "All five fail with probability 0.8⁵=0.32768.", "At least one succeeds with 1-0.32768=0.67232."], answer: "About 67.2%, at roughly five times the sample budget; independence may be false." },
    misconceptions: ["SOTA is not a property of a model in general.", "A benchmark verifier can be weak, leaked, or optimized against."],
    lab: { kind: "benchmark", title: "Leaderboard stress test", instruction: "Change sample budget, subgroup mix, latency cap, and judge error; watch rankings move." },
    retrieval: ["List the minimum qualifiers for a SOTA claim.", "Why can pass@k hide cost?", "What is ecological validity?"],
    researchLimit: "Evaluations lag deployment, and measuring adaptive agents without teaching them the test remains difficult.",
    sourceIds: ["helm", "livebench", "hamming-art", "emergence-mirage"],
  },
  {
    id: 20,
    level: "AI 401",
    slug: "safety-and-interpretability",
    title: "Optimization pressure finds the cracks in our measurements",
    shortTitle: "Safety and interpretability",
    question: "Can a stronger critic or a punishment for reward hacking solve the verifier problem?",
    summary: "Interpretability, robustness, oversight, privacy, and tool security address different risks; recursive criticism still needs grounded evidence and trusted boundaries.",
    status: "active-program",
    asOf: "2026-08-15",
    duration: 44,
    prerequisites: ["post-training", "evaluation-science"],
    objectives: ["Distinguish specification gaming from verifier compromise", "Explain why checking can be easier or harder than generation", "Threat-model a tool-using model"],
    analogy: { useful: "A verifier is a lock tested by an adaptive locksmith; optimization pressure searches for the easiest accepted path.", boundary: "Not every generator must be less capable than its checker: formal proof checking can be cheap even when proof discovery is hard. The asymmetry depends on the domain." },
    formal: { notation: "proxy reward r̃(s,a)≠intended utility U(s,a); oversight observes channel O(h), not full state h", explanation: "Punishing known hacks updates a finite test set. The optimizer can find unmeasured variants, corrupt the channel, or exploit ambiguity. Defense requires layered specifications, isolated permissions, independent evidence, and uncertainty—not one universal critic." },
    workedExample: { prompt: "A cleaner robot gets +1 for each item placed in a bin, including items it removes and replaces.", steps: ["Intended utility rewards newly cleaned items.", "Proxy reward counts placement events.", "Cycling one item produces unbounded proxy reward without cleaning more."], answer: "The behavior optimizes the written measurement. Penalizing this one loop does not prove the revised proxy equals the intended goal." },
    misconceptions: ["The real world is not an unhackable verifier; sensors, institutions, and humans are attack surfaces.", "A verifier need not be universally smarter than the generator, but weak tests remain weak evidence."],
    lab: { kind: "search", title: "Verifier red team", instruction: "Patch successive reward loopholes and track which attack class remains unmeasured." },
    retrieval: ["Give a domain where checking is easier than generation.", "Why does punishing observed hacks not solve Goodhart-style failure?", "What permission boundary should a tool agent have?"],
    researchLimit: "Scalable oversight for novel, high-stakes, hard-to-verify work remains open; interpretability methods do not yet offer complete causal audits.",
    sourceIds: ["reward-tampering", "constitutional-ai", "process-supervision", "hamming-art"],
  },
  {
    id: 21,
    level: "AI 404",
    slug: "research-frontiers",
    title: "The frontier is a set of unsolved interfaces",
    shortTitle: "Research frontiers",
    question: "Which less-hyped directions could change how systems learn and generalize?",
    summary: "Causal representation, neurosymbolic inference, continual learning, active experimentation, Bayesian optimization, and open-ended learning attack different bottlenecks.",
    status: "frontier-snapshot",
    asOf: "2026-08-15",
    duration: 46,
    prerequisites: ["world-models", "safety-and-interpretability"],
    objectives: ["Map six research programs to their target failure", "Distinguish an occupied framing from a plausible gap", "Write a kill criterion before a method claim"],
    analogy: { useful: "Instead of one expanding circle, picture a graph of imperfect instruments: observation, representation, intervention, logic, memory, and search can each extend or corrupt the others.", boundary: "Chaining modules does not guarantee compounding progress; errors, incentives, and compute costs can compound faster than knowledge." },
    formal: { notation: "causal: P(Y|do(X=x)); continual: minimize L_new+λΣ_i F_i(θ_i-θ_i*)²; BO: x_{t+1}=argmax acquisition(x)", explanation: "Causal learning targets intervention-stable structure. EWC regularizes parameters using an importance estimate. Bayesian optimization selects expensive experiments from a probabilistic surrogate. Each formalism encodes assumptions that can fail." },
    workedExample: { prompt: "A correlation P(Y|X) changes after intervention, but P(Y|do(X)) is required.", steps: ["Observation can mix causal effect and confounding.", "Intervention breaks incoming causes of X in the causal model.", "The two distributions need not agree."], answer: "More observational scale alone cannot identify every causal effect without assumptions or interventions." },
    misconceptions: ["Cross-domain analogy is a hypothesis source, not a wormhole to validated theory.", "Self-generated data expands competence only when filtering, coverage, and evaluation remain trustworthy."],
    lab: { kind: "geometry", title: "Frontier map", instruction: "Choose a failure and trace which research programs target it, plus their assumptions and kill tests." },
    retrieval: ["What does do(X) distinguish from conditioning on X?", "How does EWC try to reduce forgetting?", "Why is novelty search insufficient for usefulness?"],
    researchLimit: "These programs are active and overlapping; novelty requires a current literature and patent audit plus a reproducible negative baseline.",
    sourceIds: ["causal-rep", "deepproblog", "ewc", "poet"],
  },
  {
    id: 22,
    level: "AI 404",
    slug: "research-practicum",
    title: "Research begins with a result you are willing to kill",
    shortTitle: "Research practicum",
    question: "How do I turn a compelling intuition into a defensible research direction?",
    summary: "Reproduce first, trace limitations forward, construct adversarial overlap tests, and propose a bounded extension with failure criteria.",
    status: "established",
    duration: 52,
    prerequisites: ["research-frontiers"],
    objectives: ["Write a reproducible baseline contract", "Trace a limitation through later work", "Define novelty, feasibility, and kill gates separately"],
    analogy: { useful: "A research idea is a suspect, not a hero: gather alibis, test contradictions, and try to disprove the preferred story.", boundary: "Falsification is not performative pessimism. Negative evidence must use a fair implementation, relevant metric, and sufficient power." },
    formal: { notation: "claim=(task,method,baseline,metric,regime); Δ=m_new-m_base with uncertainty; kill if CI(Δ) includes material inferiority", explanation: "A claim becomes inspectable when every noun is operationalized. Reproduction calibrates the apparatus. Literature and patent overlap tests bound novelty. Predeclared kill criteria prevent moving the goalposts." },
    workedExample: { prompt: "A new method scores 81.0±1.5 versus baseline 80.5±0.4 over three seeds.", steps: ["Point gain is 0.5.", "Uncertainty intervals overlap substantially.", "Three seeds and unequal variance do not support a confident superiority claim."], answer: "Report the result as inconclusive, inspect variance and protocol, and run a powered comparison before claiming improvement." },
    misconceptions: ["A plausible mechanism is not evidence of novelty.", "A leaderboard gain without protocol and uncertainty is not a research contribution by itself."],
    lab: { kind: "benchmark", title: "Claim gate", instruction: "Enter a method claim and force it through baseline, overlap, feasibility, uncertainty, and kill checks." },
    retrieval: ["Why reproduce before extending?", "What is an occupied framing?", "Write one kill criterion for your own idea."],
    researchLimit: "No checklist can eliminate unknown prior art or implementation confounds; claims should remain proportional to the completed audit.",
    sourceIds: ["hamming-art", "make-it-stick", "helm", "bishop-prml"],
  },
];

export const moduleBySlug = new Map(modules.map((module) => [module.slug, module]));
