import type { FrontierProgram } from "./types.ts";

export const frontierPrograms: FrontierProgram[] = [
  {
    id: "ssi",
    name: "Safe Superintelligence Inc.",
    announced: "2024-06-19",
    disclosure: "opaque",
    publicRecord: "SSI describes a single-product laboratory where safety and capability are meant to advance together. Its founders have published no architecture, training recipe, model, benchmark, or safety case.",
    plausibleDirection: "Ilya Sutskever's public remarks point toward a research bet on human-like generalization, sample efficiency, continual learning, and value functions that remain useful across tasks. That is an inference from his stated problems, not a disclosed SSI method.",
    missingEvidence: "A technical artifact that defines the learning objective, a test that separates broad transfer from nearby-task saturation, and measurable gates for the claim that safety remains ahead of capability.",
    researchQuestions: [
      "What evaluation separates broad generalization from dense coverage of similar tasks?",
      "Can post-deployment learning avoid forgetting, privacy leakage, and cross-user contamination?",
      "How can weak supervisors detect strategically hidden failures in an adapting system?",
    ],
    sourceIds: ["ssi-statement", "sutskever-research-age", "weak-to-strong"],
  },
  {
    id: "thinking-machines",
    name: "Thinking Machines Lab",
    announced: "2026-05-11",
    disclosure: "partial",
    publicRecord: "The interaction-model preview describes 200 millisecond micro-turns, early multimodal fusion, and foreground and background models with shared context. The weights, training set, full ablations, and independent evaluations remain private.",
    plausibleDirection: "The research bet treats timing, interruption, silence, gaze, and correction as native learning signals. Joint human-machine work, rather than solitary benchmark scores, becomes the object to measure.",
    missingEvidence: "Controlled comparisons against equally capable turn-based systems, real joint-task outcomes, and evidence that rapid correction reduces error without teaching reflexive agreement.",
    researchQuestions: [
      "Which measurements predict joint work rather than conversational smoothness?",
      "Can a model learn from interruption without becoming overly deferential?",
      "How should foreground and background processes resolve stale or private context?",
    ],
    sourceIds: ["thinking-interaction-models"],
  },
  {
    id: "world-labs",
    name: "World Labs",
    announced: "2024-12-02",
    disclosure: "partial",
    publicRecord: "World Labs has shown persistent, navigable generated scenes and now distinguishes three functions: rendering observations, simulating action-conditioned change, and planning. The first is not evidence that the other two are solved.",
    plausibleDirection: "A coherent route runs from spatial rendering to intervention-aware simulation and then to policy testing. If those layers can share persistent objects, uncertainty, and dynamics, generated worlds may become useful training environments rather than visual demos.",
    missingEvidence: "Public action-conditioned evaluations, long-horizon identity and physics tests, and robot-transfer comparisons against conventional simulators and domain randomization.",
    researchQuestions: [
      "How should dynamics be tested under interventions rather than frame prediction alone?",
      "Can hidden state and object identity survive hours of interaction?",
      "Does a generated environment improve reliability on unseen physical tasks?",
    ],
    sourceIds: ["worldlabs-taxonomy", "vjepa", "diffusion-policy"],
  },
  {
    id: "periodic",
    name: "Periodic Labs",
    announced: "2025-09-30",
    disclosure: "opaque",
    publicRecord: "Periodic says it is building AI scientists and automated physical laboratories, starting with materials and other physical sciences. Its launch page describes experiments as a source of positive and negative data, but publishes no discovery protocol or independently replicated result.",
    plausibleDirection: "Automated experiments can close a loop that internet-scale learning cannot: choose a measurement, act on matter, observe a noisy result, and update the next choice. Failed experiments may be as informative as successful ones.",
    missingEvidence: "Experiment throughput, apparatus-drift controls, preregistered discovery criteria, released negative results, and external replication of a selected claim.",
    researchQuestions: [
      "How should delayed and equipment-dependent measurements enter a reward?",
      "Which active-learning strategy works when experiments are costly and batched?",
      "How are simulator error and measurement error kept from reinforcing one another?",
    ],
    sourceIds: ["periodic-labs-statement", "alphafold3", "reward-tampering"],
  },
  {
    id: "reflection",
    name: "Reflection AI",
    announced: "2025-03-07",
    disclosure: "opaque",
    publicRecord: "Reflection proposes using reinforcement learning to solve autonomous coding, then transferring the resulting approach to other computer work. Its public agenda is specific about the bet but does not yet supply the promised frontier weights, training report, or reproducible environment suite.",
    plausibleDirection: "Code offers executable feedback, long tasks, tools, and abundant failure traces. It is a strong laboratory for agent training. Whether the resulting skills transfer outside verifier-rich software work is the central uncertainty.",
    missingEvidence: "A public model and harness, long-horizon reliability tests, controlled transfer beyond code, and accounting that separates model gains from search, tools, memory, and scaffolding.",
    researchQuestions: [
      "Which coding skills transfer to other computer work, and which remain domain-bound?",
      "How does long-horizon training cope with sparse or gameable rewards?",
      "How much capability belongs to the model rather than the surrounding harness?",
    ],
    sourceIds: ["reflection-path", "ppo", "react"],
  },
  {
    id: "harmonic",
    name: "Harmonic",
    announced: "2025-10-01",
    disclosure: "technical-report",
    publicRecord: "Harmonic's Aristotle report describes Lean proof search, informal reasoning that proposes and formalizes lemmas, and a dedicated geometry solver. A proof accepted by Lean is strong evidence for the formal statement, but the model weights and full training system remain closed.",
    plausibleDirection: "Formal domains support a productive loop between proposal, search, and cheap machine checking. The near-term frontier is less about a universal critic than about expanding the set of tasks with trustworthy specifications.",
    missingEvidence: "Open weights and training details, tests of conjecture choice, safeguards against mistranslating informal problems, and evidence for transfer to code or science with incomplete specifications.",
    researchQuestions: [
      "Can a system select important conjectures rather than only prove given statements?",
      "How can formalization be checked for silent changes in meaning?",
      "What transfers when the target domain lacks complete machine-readable rules?",
    ],
    sourceIds: ["aristotle-report", "alphageometry", "deepproblog"],
  },
];
