import type { Source } from "./types.ts";

export const sources: Source[] = [
  {
    id: "bishop-prml",
    title: "Pattern Recognition and Machine Learning",
    creators: "Christopher M. Bishop",
    year: 2006,
    kind: "close-read-book",
    locator: "Chapters 1-5 and 8-13; PDF pages 23-698",
    note: "Formal backbone for probability, decision theory, neural networks, latent variables, graphical models, and sequential data.",
  },
  {
    id: "welch-ai",
    title: "The Illustrated Guide to AI",
    creators: "Stephen Welch",
    year: 2025,
    kind: "close-read-book",
    locator: "Chapters 1-9; PDF pages 13-352",
    note: "Visual intuition for perceptrons, backpropagation, scale, interpretability, attention, and generation. Diagrams here are independently redrawn.",
  },
  {
    id: "hamming-art",
    title: "The Art of Doing Science and Engineering",
    creators: "Richard W. Hamming",
    year: 1997,
    kind: "close-read-book",
    locator: "Chapters 9, 13, 18-20, and 27-30; PDF pages 66-224",
    note: "Research practice, simulation, information, system design, and the warning that measurement choices reshape behavior.",
  },
  {
    id: "make-it-stick",
    title: "Make It Stick",
    creators: "Peter C. Brown, Henry L. Roediger III, and Mark A. McDaniel",
    year: 2014,
    kind: "close-read-book",
    locator: "Chapters 1-8; PDF pages 18-267",
    note: "Learning design basis for retrieval, spacing, interleaving, calibration, and productive difficulty.",
  },
  {
    id: "deep-learning-book",
    title: "Deep Learning",
    creators: "Ian Goodfellow, Yoshua Bengio, and Aaron Courville",
    year: 2016,
    kind: "book",
    locator: "Chapters 5-10 and 14-20",
    url: "https://www.deeplearningbook.org/",
    note: "A standard reference for optimization, deep feedforward networks, sequence models, representation learning, and generative modeling.",
  },
  {
    id: "sutton-barto",
    title: "Reinforcement Learning: An Introduction",
    creators: "Richard S. Sutton and Andrew G. Barto",
    year: 2018,
    kind: "book",
    locator: "Second edition, Chapters 3-13",
    url: "http://incompleteideas.net/book/the-book-2nd.html",
    note: "The main textbook anchor for returns, value functions, temporal-difference learning, policy gradients, planning, and the limits of tabular examples.",
  },
  {
    id: "murphy-pml",
    title: "Probabilistic Machine Learning: An Introduction",
    creators: "Kevin P. Murphy",
    year: 2022,
    kind: "book",
    locator: "Chapters 2-14 and 17-20",
    url: "https://probml.github.io/pml-book/book1.html",
    note: "A modern probabilistic treatment of supervised learning, latent variables, deep networks, uncertainty, and model evaluation.",
  },
  {
    id: "understanding-deep-learning",
    title: "Understanding Deep Learning",
    creators: "Simon J. D. Prince",
    year: 2023,
    kind: "book",
    locator: "Chapters 3-12 and 15-19",
    url: "https://udlbook.github.io/udlbook/",
    note: "A contemporary bridge from neural-network mechanics to transformers, generative models, reinforcement learning, and interpretability.",
  },
  {
    id: "aima",
    title: "Artificial Intelligence: A Modern Approach",
    creators: "Stuart Russell and Peter Norvig",
    year: 2021,
    kind: "book",
    locator: "Fourth edition, Parts II-VII",
    url: "https://aima.eecs.berkeley.edu/",
    note: "A broad map of search, uncertainty, learning, language, robotics, and agent design that keeps AI wider than neural prediction alone.",
  },
  {
    id: "elements-statistical-learning",
    title: "The Elements of Statistical Learning",
    creators: "Trevor Hastie, Robert Tibshirani, and Jerome Friedman",
    year: 2009,
    kind: "book",
    locator: "Second edition, Chapters 2-10 and 15-18",
    url: "https://hastie.su.domains/ElemStatLearn/",
    note: "A classical reference for bias and variance, linear methods, trees, boosting, kernels, unsupervised learning, and model assessment.",
  },
  {
    id: "pearl-causality",
    title: "Causality: Models, Reasoning, and Inference",
    creators: "Judea Pearl",
    year: 2009,
    kind: "book",
    locator: "Second edition, Chapters 1-4 and 7",
    url: "https://www.cambridge.org/core/books/causality/B0046844FAE10CBF274D4ACBDAEB5F5B",
    note: "The formal reference for structural causal models, intervention, identification, and why prediction alone does not establish causal structure.",
  },
  {
    id: "mackay-information",
    title: "Information Theory, Inference, and Learning Algorithms",
    creators: "David J. C. MacKay",
    year: 2003,
    kind: "book",
    locator: "Parts II-VI",
    url: "https://www.inference.org.uk/itprnn/book.html",
    note: "An unusually connected treatment of information, Bayesian inference, neural networks, sampling, and coding with worked mathematical intuition.",
  },
  {
    id: "mit-ml-intro",
    title: "6.390 Introduction to Machine Learning",
    creators: "MIT Open Learning Library",
    year: 2025,
    kind: "course",
    locator: "Course sequence and exercises",
    url: "https://openlearninglibrary.mit.edu/courses/course-v1:MITx+6.036+1T2019/about",
    note: "A structured route through prediction, generalization, neural networks, and sequential decision-making.",
  },
  {
    id: "stanford-cs229",
    title: "CS229 Machine Learning",
    creators: "Stanford University",
    year: 2025,
    kind: "course",
    locator: "Syllabus and notes",
    url: "https://cs229.stanford.edu/",
    note: "Mathematical reference for supervised learning, optimization, generalization, and unsupervised learning.",
  },
  {
    id: "bert",
    title: "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding",
    creators: "Jacob Devlin, Ming-Wei Chang, Kenton Lee, and Kristina Toutanova",
    year: 2019,
    kind: "paper",
    locator: "NAACL 2019, Sections 3-4",
    url: "https://aclanthology.org/N19-1423/",
    note: "Masked-token pretraining: one important self-supervised objective, not the definition of all self-supervision.",
  },
  {
    id: "simclr",
    title: "A Simple Framework for Contrastive Learning of Visual Representations",
    creators: "Ting Chen, Simon Kornblith, Mohammad Norouzi, and Geoffrey Hinton",
    year: 2020,
    kind: "paper",
    locator: "ICML 2020",
    url: "https://proceedings.mlr.press/v119/chen20j.html",
    note: "Shows a non-reconstructive contrastive self-supervised objective.",
  },
  {
    id: "mae",
    title: "Masked Autoencoders Are Scalable Vision Learners",
    creators: "Kaiming He et al.",
    year: 2022,
    kind: "paper",
    locator: "CVPR 2022",
    url: "https://openaccess.thecvf.com/content/CVPR2022/html/He_Masked_Autoencoders_Are_Scalable_Vision_Learners_CVPR_2022_paper.html",
    note: "Masked image reconstruction and the role of high masking ratios.",
  },
  {
    id: "vae",
    title: "Auto-Encoding Variational Bayes",
    creators: "Diederik P. Kingma and Max Welling",
    year: 2014,
    kind: "paper",
    locator: "ICLR 2014",
    url: "https://arxiv.org/abs/1312.6114",
    note: "Latent-variable generative modeling with a variational lower bound.",
  },
  {
    id: "gan",
    title: "Generative Adversarial Nets",
    creators: "Ian Goodfellow et al.",
    year: 2014,
    kind: "paper",
    locator: "NeurIPS 2014",
    url: "https://papers.nips.cc/paper/5423-generative-adversarial-nets",
    note: "Generator-discriminator game and its distribution-matching interpretation.",
  },
  {
    id: "ddpm",
    title: "Denoising Diffusion Probabilistic Models",
    creators: "Jonathan Ho, Ajay Jain, and Pieter Abbeel",
    year: 2020,
    kind: "paper",
    locator: "NeurIPS 2020",
    url: "https://papers.nips.cc/paper/2020/hash/4c5bcfec8584af0d967f1ab10179ca4b-Abstract.html",
    note: "A diffusion objective and iterative denoising sampler.",
  },
  {
    id: "flow-matching",
    title: "Flow Matching for Generative Modeling",
    creators: "Yaron Lipman et al.",
    year: 2023,
    kind: "paper",
    locator: "ICLR 2023",
    url: "https://openreview.net/forum?id=PqvMRDCJT9t",
    note: "Simulation-free training of continuous normalizing flows via vector-field regression.",
  },
  {
    id: "dqn",
    title: "Human-level control through deep reinforcement learning",
    creators: "Volodymyr Mnih et al.",
    year: 2015,
    kind: "paper",
    locator: "Nature 518",
    url: "https://www.nature.com/articles/nature14236",
    note: "Value-based deep RL from pixels, with experience replay and target networks.",
  },
  {
    id: "ppo",
    title: "Proximal Policy Optimization Algorithms",
    creators: "John Schulman et al.",
    year: 2017,
    kind: "paper",
    locator: "arXiv:1707.06347",
    url: "https://arxiv.org/abs/1707.06347",
    note: "A widely used clipped policy-gradient objective.",
  },
  {
    id: "cql",
    title: "Conservative Q-Learning for Offline Reinforcement Learning",
    creators: "Aviral Kumar et al.",
    year: 2020,
    kind: "paper",
    locator: "NeurIPS 2020",
    url: "https://proceedings.neurips.cc/paper/2020/hash/0d2b2061826a5df3221116a5085a6052-Abstract.html",
    note: "Offline RL method designed to reduce overestimation on out-of-distribution actions.",
  },
  {
    id: "dreamer",
    title: "Mastering Diverse Domains through World Models",
    creators: "Danijar Hafner et al.",
    year: 2023,
    kind: "paper",
    locator: "arXiv:2301.04104",
    url: "https://arxiv.org/abs/2301.04104",
    note: "DreamerV3 learns a latent world model and improves behavior through imagined trajectories.",
  },
  {
    id: "attention",
    title: "Attention Is All You Need",
    creators: "Ashish Vaswani et al.",
    year: 2017,
    kind: "paper",
    locator: "NeurIPS 2017",
    url: "https://papers.nips.cc/paper/7181-attention-is-all-you-need",
    note: "Transformer architecture, scaled dot-product attention, and positional encodings.",
  },
  {
    id: "gpt3",
    title: "Language Models are Few-Shot Learners",
    creators: "Tom B. Brown et al.",
    year: 2020,
    kind: "paper",
    locator: "NeurIPS 2020",
    url: "https://papers.nips.cc/paper/2020/hash/1457c0d6bfcb4967418bfb8ac142f64a-Abstract.html",
    note: "Autoregressive scaling and in-context task behavior without parameter updates at inference.",
  },
  {
    id: "rope",
    title: "RoFormer: Enhanced Transformer with Rotary Position Embedding",
    creators: "Jianlin Su et al.",
    year: 2024,
    kind: "paper",
    locator: "Neurocomputing 568",
    url: "https://arxiv.org/abs/2104.09864",
    note: "Rotary position encoding as relative angular structure in queries and keys.",
  },
  {
    id: "induction-heads",
    title: "In-context Learning and Induction Heads",
    creators: "Catherine Olsson et al.",
    year: 2022,
    kind: "paper",
    locator: "Transformer Circuits",
    url: "https://transformer-circuits.pub/2022/in-context-learning-and-induction-heads/index.html",
    note: "Mechanistic evidence connecting induction heads to a class of in-context pattern completion.",
  },
  {
    id: "lost-middle",
    title: "Lost in the Middle: How Language Models Use Long Contexts",
    creators: "Nelson F. Liu et al.",
    year: 2024,
    kind: "paper",
    locator: "TACL 12",
    url: "https://aclanthology.org/2024.tacl-1.9/",
    note: "Long context availability does not imply uniform use of information at every position.",
  },
  {
    id: "scaling-laws",
    title: "Scaling Laws for Neural Language Models",
    creators: "Jared Kaplan et al.",
    year: 2020,
    kind: "paper",
    locator: "arXiv:2001.08361",
    url: "https://arxiv.org/abs/2001.08361",
    note: "Empirical power-law relationships over a measured regime, not a law of unlimited intelligence.",
  },
  {
    id: "chinchilla",
    title: "Training Compute-Optimal Large Language Models",
    creators: "Jordan Hoffmann et al.",
    year: 2022,
    kind: "paper",
    locator: "NeurIPS 2022",
    url: "https://papers.nips.cc/paper_files/paper/2022/hash/c1e2faff6f588870935f114ebe04a3e5-Abstract-Conference.html",
    note: "Compute-optimal allocation between model size and training tokens under the study's assumptions.",
  },
  {
    id: "datacomp",
    title: "DataComp: In search of the next generation of multimodal datasets",
    creators: "Samir Yitzhak Gadre et al.",
    year: 2023,
    kind: "paper",
    locator: "NeurIPS 2023 Datasets and Benchmarks",
    url: "https://arxiv.org/abs/2304.14108",
    note: "A controlled benchmark showing how dataset filtering and curation choices change contrastive image-text model performance.",
  },
  {
    id: "sae-monosemanticity",
    title: "Scaling Monosemanticity: Extracting Interpretable Features from Claude 3 Sonnet",
    creators: "Adly Templeton et al.",
    year: 2024,
    kind: "researcher-note",
    locator: "Transformer Circuits, 2024",
    url: "https://transformer-circuits.pub/2024/scaling-monosemanticity/index.html",
    note: "A large sparse-autoencoder feature analysis that provides hypotheses and interventions while leaving feature completeness and uniqueness open.",
  },
  {
    id: "gnome",
    title: "Scaling deep learning for materials discovery",
    creators: "Amil Merchant et al.",
    year: 2023,
    kind: "paper",
    locator: "Nature 624, 80-85",
    url: "https://www.nature.com/articles/s41586-023-06735-9",
    note: "The GNoME graph-network program for proposing stable crystal structures, paired with explicit downstream validation requirements.",
  },
  {
    id: "mattergen",
    title: "MatterGen: a generative model for inorganic materials design",
    creators: "Cheng-Hao Fu et al.",
    year: 2024,
    kind: "paper",
    locator: "arXiv:2401.00096",
    url: "https://arxiv.org/abs/2401.00096",
    note: "A diffusion-based materials generator that conditions candidate structures on target properties and requires physical validation beyond generation metrics.",
  },
  {
    id: "switch",
    title: "Switch Transformers: Scaling to Trillion Parameter Models with Simple and Efficient Sparsity",
    creators: "William Fedus, Barret Zoph, and Noam Shazeer",
    year: 2022,
    kind: "paper",
    locator: "JMLR 23",
    url: "https://www.jmlr.org/papers/v23/21-0998.html",
    note: "Sparse mixture-of-experts routing and the difference between total and active parameters.",
  },
  {
    id: "flashattention",
    title: "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness",
    creators: "Tri Dao et al.",
    year: 2022,
    kind: "paper",
    locator: "NeurIPS 2022",
    url: "https://papers.nips.cc/paper_files/paper/2022/hash/67d57c32e20fd0a7a302cb81d36e40d5-Abstract-Conference.html",
    note: "Exact attention reorganized to reduce memory traffic; an implementation improvement, not a new learning objective.",
  },
  {
    id: "lora",
    title: "LoRA: Low-Rank Adaptation of Large Language Models",
    creators: "Edward J. Hu et al.",
    year: 2022,
    kind: "paper",
    locator: "ICLR 2022",
    url: "https://openreview.net/forum?id=nZeVKeeFYf9",
    note: "Parameter-efficient adaptation through learned low-rank weight updates.",
  },
  {
    id: "instructgpt",
    title: "Training language models to follow instructions with human feedback",
    creators: "Long Ouyang et al.",
    year: 2022,
    kind: "paper",
    locator: "NeurIPS 2022",
    url: "https://papers.nips.cc/paper_files/paper/2022/hash/b1efde53be364a73914f58805a001731-Abstract-Conference.html",
    note: "Supervised demonstrations, preference modeling, and PPO-based RLHF in one concrete pipeline.",
  },
  {
    id: "constitutional-ai",
    title: "Constitutional AI: Harmlessness from AI Feedback",
    creators: "Yuntao Bai et al.",
    year: 2022,
    kind: "paper",
    locator: "arXiv:2212.08073",
    url: "https://arxiv.org/abs/2212.08073",
    note: "Self-critique/revision followed by preference learning from AI feedback; not an immutable law in the loss function.",
  },
  {
    id: "dpo",
    title: "Direct Preference Optimization: Your Language Model is Secretly a Reward Model",
    creators: "Rafael Rafailov et al.",
    year: 2023,
    kind: "paper",
    locator: "NeurIPS 2023",
    url: "https://papers.nips.cc/paper_files/paper/2023/hash/a85b405ed65c6477a4fe8302b5e06ce7-Abstract-Conference.html",
    note: "A preference objective that avoids fitting and sampling from an explicit reward model during training.",
  },
  {
    id: "process-supervision",
    title: "Let’s Verify Step by Step",
    creators: "Hunter Lightman et al.",
    year: 2023,
    kind: "paper",
    locator: "arXiv:2305.20050",
    url: "https://arxiv.org/abs/2305.20050",
    note: "Outcome versus process supervision on mathematical reasoning.",
  },
  {
    id: "self-consistency",
    title: "Self-Consistency Improves Chain of Thought Reasoning in Language Models",
    creators: "Xuezhi Wang et al.",
    year: 2023,
    kind: "paper",
    locator: "ICLR 2023",
    url: "https://openreview.net/forum?id=1PL1NIMMrw",
    note: "Sampling multiple reasoning paths and marginalizing answers; inference-time search without online RL updates.",
  },
  {
    id: "tree-thoughts",
    title: "Tree of Thoughts: Deliberate Problem Solving with Large Language Models",
    creators: "Shunyu Yao et al.",
    year: 2023,
    kind: "paper",
    locator: "NeurIPS 2023",
    url: "https://papers.nips.cc/paper_files/paper/2023/hash/271db9922b8d1f4dd7aaef84ed5ac703-Abstract-Conference.html",
    note: "A prompting and search framework over intermediate text states; not automatically RL or MCTS.",
  },
  {
    id: "deepseek-r1",
    title: "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning",
    creators: "DeepSeek-AI",
    year: 2025,
    kind: "paper",
    locator: "arXiv:2501.12948",
    url: "https://arxiv.org/abs/2501.12948",
    note: "A dated, documented reasoning-post-training pipeline. Its generation process should not be redescribed as literal MCTS without evidence.",
  },
  {
    id: "clip",
    title: "Learning Transferable Visual Models From Natural Language Supervision",
    creators: "Alec Radford et al.",
    year: 2021,
    kind: "paper",
    locator: "ICML 2021",
    url: "https://proceedings.mlr.press/v139/radford21a.html",
    note: "Contrastive image-text representation learning from paired web data.",
  },
  {
    id: "react",
    title: "ReAct: Synergizing Reasoning and Acting in Language Models",
    creators: "Shunyu Yao et al.",
    year: 2023,
    kind: "paper",
    locator: "ICLR 2023",
    url: "https://openreview.net/forum?id=WE_vluYUL-X",
    note: "Interleaves verbal reasoning traces with environment actions and observations.",
  },
  {
    id: "ijepa",
    title: "Self-Supervised Learning From Images With a Joint-Embedding Predictive Architecture",
    creators: "Mahmoud Assran et al.",
    year: 2023,
    kind: "paper",
    locator: "CVPR 2023",
    url: "https://openaccess.thecvf.com/content/CVPR2023/html/Assran_Self-Supervised_Learning_From_Images_With_a_Joint-Embedding_Predictive_Architecture_CVPR_2023_paper.html",
    note: "JEPA is itself self-supervised and predicts target representations rather than pixels.",
  },
  {
    id: "vjepa",
    title: "Revisiting Feature Prediction for Learning Visual Representations from Video",
    creators: "Adrien Bardes et al.",
    year: 2024,
    kind: "paper",
    locator: "arXiv:2404.08471",
    url: "https://arxiv.org/abs/2404.08471",
    note: "V-JEPA learns video representations by masked prediction in representation space; not a universal physical-control solution.",
  },
  {
    id: "diffusion-policy",
    title: "Diffusion Policy: Visuomotor Policy Learning via Action Diffusion",
    creators: "Cheng Chi et al.",
    year: 2023,
    kind: "paper",
    locator: "RSS 2023",
    url: "https://diffusion-policy.cs.columbia.edu/",
    note: "Counterexample to the claim that denoising mechanisms fail for physical control.",
  },
  {
    id: "rt2",
    title: "RT-2: Vision-Language-Action Models Transfer Web Knowledge to Robotic Control",
    creators: "Brianna Zitkovich et al.",
    year: 2023,
    kind: "paper",
    locator: "CoRL 2023",
    url: "https://proceedings.mlr.press/v229/zitkovich23a.html",
    note: "Robot actions represented as tokens in a vision-language-action model.",
  },
  {
    id: "open-x",
    title: "Open X-Embodiment: Robotic Learning Datasets and RT-X Models",
    creators: "Open X-Embodiment Collaboration",
    year: 2024,
    kind: "paper",
    locator: "ICRA 2024",
    url: "https://arxiv.org/abs/2310.08864",
    note: "Cross-robot dataset and model study, useful for discussing embodiment heterogeneity and transfer limits.",
  },
  {
    id: "alphafold3",
    title: "Accurate structure prediction of biomolecular interactions with AlphaFold 3",
    creators: "Josh Abramson et al.",
    year: 2024,
    kind: "paper",
    locator: "Nature 630",
    url: "https://www.nature.com/articles/s41586-024-07487-w",
    note: "Uses a diffusion-based architecture; it is not evidence that open-ended RL produced the discovery.",
  },
  {
    id: "alphadev",
    title: "Faster sorting algorithms discovered using deep reinforcement learning",
    creators: "Daniel J. Mankowitz et al.",
    year: 2023,
    kind: "paper",
    locator: "Nature 618",
    url: "https://www.nature.com/articles/s41586-023-06004-9",
    note: "Bounded discovery in a precisely measured instruction-level environment.",
  },
  {
    id: "alphageometry",
    title: "Solving olympiad geometry without human demonstrations",
    creators: "Trieu H. Trinh et al.",
    year: 2024,
    kind: "paper",
    locator: "Nature 625",
    url: "https://www.nature.com/articles/s41586-023-06747-5",
    note: "Neuro-symbolic geometry solving with synthetic theorem generation; not simply RL self-play.",
  },
  {
    id: "helm",
    title: "Holistic Evaluation of Language Models",
    creators: "Percy Liang et al.",
    year: 2023,
    kind: "paper",
    locator: "TMLR",
    url: "https://openreview.net/forum?id=iO4LZibEqW",
    note: "Multi-metric, scenario-based evaluation and explicit coverage of limitations.",
  },
  {
    id: "livebench",
    title: "LiveBench: A Challenging, Contamination-Free LLM Benchmark",
    creators: "Colin White et al.",
    year: 2024,
    kind: "paper",
    locator: "arXiv:2406.19314",
    url: "https://arxiv.org/abs/2406.19314",
    note: "Frequently refreshed questions as one response to test-set contamination, with its own scope limits.",
  },
  {
    id: "emergence-mirage",
    title: "Are Emergent Abilities of Large Language Models a Mirage?",
    creators: "Rylan Schaeffer, Brando Miranda, and Sanmi Koyejo",
    year: 2023,
    kind: "paper",
    locator: "NeurIPS 2023",
    url: "https://papers.nips.cc/paper_files/paper/2023/hash/adc98a266f45005c403b8311ca7e8bd7-Abstract-Conference.html",
    note: "Shows how discontinuous metrics can create apparent sharp emergence from smooth underlying changes.",
  },
  {
    id: "reward-tampering",
    title: "Defining and Characterizing Reward Hacking",
    creators: "Joar Skalse et al.",
    year: 2022,
    kind: "paper",
    locator: "NeurIPS 2022",
    url: "https://arxiv.org/abs/2209.13085",
    note: "Formal distinctions among reward misspecification and hacking behaviors.",
  },
  {
    id: "causal-rep",
    title: "Toward Causal Representation Learning",
    creators: "Bernhard Schölkopf et al.",
    year: 2021,
    kind: "paper",
    locator: "Proceedings of the IEEE 109(5)",
    url: "https://doi.org/10.1109/JPROC.2021.3058954",
    note: "Research program connecting learned representations with causal variables and mechanisms.",
  },
  {
    id: "deepproblog",
    title: "DeepProbLog: Neural Probabilistic Logic Programming",
    creators: "Robin Manhaeve et al.",
    year: 2018,
    kind: "paper",
    locator: "NeurIPS 2018",
    url: "https://papers.nips.cc/paper/2018/hash/dc5d637ed5e62c36ecb73b654b05ba2a-Abstract.html",
    note: "A concrete neurosymbolic system integrating neural predicates and probabilistic logic.",
  },
  {
    id: "ewc",
    title: "Overcoming catastrophic forgetting in neural networks",
    creators: "James Kirkpatrick et al.",
    year: 2017,
    kind: "paper",
    locator: "PNAS 114(13)",
    url: "https://www.pnas.org/doi/10.1073/pnas.1611835114",
    note: "Elastic Weight Consolidation and one approach to continual-learning interference.",
  },
  {
    id: "poet",
    title: "Paired Open-Ended Trailblazer (POET): Endlessly Generating Increasingly Complex and Diverse Learning Environments",
    creators: "Rui Wang et al.",
    year: 2019,
    kind: "paper",
    locator: "arXiv:1901.01753",
    url: "https://arxiv.org/abs/1901.01753",
    note: "Co-evolving environments and agents as a bounded example of open-ended learning research.",
  },
  {
    id: "owasp-prompt-injection",
    title: "LLM01:2025 Prompt Injection",
    creators: "OWASP Gen AI Security Project",
    year: 2025,
    kind: "official",
    locator: "OWASP Top 10 for LLM Applications, LLM01:2025",
    url: "https://genai.owasp.org/llmrisk/llm01-prompt-injection/",
    note: "Defines direct and indirect prompt injection and recommends trust boundaries, constrained privileges, validated output formats, separation of untrusted content, human approval for high-risk actions, and adversarial testing.",
  },
  {
    id: "owasp-excessive-agency",
    title: "LLM06:2025 Excessive Agency",
    creators: "OWASP Gen AI Security Project",
    year: 2025,
    kind: "official",
    locator: "OWASP Top 10 for LLM Applications, LLM06:2025",
    url: "https://genai.owasp.org/llmrisk/llm062025-excessive-agency/",
    note: "Traces agent harm to excessive functionality, permissions, or autonomy and provides system-level mitigations for tool-using applications.",
  },
  {
    id: "nist-genai-profile",
    title: "Artificial Intelligence Risk Management Framework: Generative Artificial Intelligence Profile",
    creators: "National Institute of Standards and Technology",
    year: 2024,
    kind: "official",
    locator: "NIST AI 600-1, final publication, July 2024",
    url: "https://doi.org/10.6028/NIST.AI.600-1",
    note: "A cross-sector framework for governing, mapping, measuring, and managing generative-AI risks across the system lifecycle.",
  },
  {
    id: "ssi-statement",
    title: "Safe Superintelligence Inc.",
    creators: "Ilya Sutskever, Daniel Gross, and Daniel Levy",
    year: 2024,
    kind: "official",
    locator: "Company statement, 19 June 2024",
    url: "https://ssi.inc/",
    note: "Defines SSI as a single-product laboratory pursuing safety and capability together. It discloses no architecture, benchmark, model, or safety gate.",
  },
  {
    id: "sutskever-research-age",
    title: "We're moving from the age of scaling to the age of research",
    creators: "Ilya Sutskever, interviewed by Dwarkesh Patel",
    year: 2025,
    kind: "researcher-note",
    locator: "Full interview transcript, 25 November 2025",
    url: "https://www.dwarkesh.com/p/ilya-sutskever-2",
    note: "Public hypotheses about weak generalization, sample efficiency, continual learning, value functions, and learning through deployment. These are not SSI method disclosures.",
  },
  {
    id: "weak-to-strong",
    title: "Weak-to-Strong Generalization: Eliciting Strong Capabilities With Weak Supervision",
    creators: "Collin Burns et al.",
    year: 2023,
    kind: "paper",
    locator: "arXiv:2312.09390",
    url: "https://arxiv.org/abs/2312.09390",
    note: "An empirical study of learning from weaker supervisors. Its partial recovery results frame scalable oversight as an open problem rather than a solved recipe.",
  },
  {
    id: "thinking-interaction-models",
    title: "Interaction Models: A Scalable Approach to Human-AI Collaboration",
    creators: "Thinking Machines Lab",
    year: 2026,
    kind: "official",
    locator: "Research preview, 11 May 2026",
    url: "https://thinkingmachines.ai/blog/interaction-models/",
    note: "Discloses a native multimodal interaction design built around micro-turns and foreground-background models, while leaving weights, data, and independent evaluation unavailable.",
  },
  {
    id: "worldlabs-taxonomy",
    title: "A Functional Taxonomy of World Models",
    creators: "World Labs",
    year: 2026,
    kind: "researcher-note",
    locator: "Technical essay, 3 June 2026",
    url: "https://www.worldlabs.ai/blog/taxonomy-of-world-models",
    note: "Separates renderers, simulators, and planners. The taxonomy makes clear that visual consistency alone does not establish causal dynamics or control competence.",
  },
  {
    id: "periodic-labs-statement",
    title: "Introducing Periodic Labs",
    creators: "Periodic Labs",
    year: 2025,
    kind: "official",
    locator: "Company statement, 30 September 2025",
    url: "https://periodic.com/",
    note: "Proposes autonomous physical laboratories as an experiment-and-learning loop for AI scientists. No public discovery benchmark, protocol, or independently replicated result is provided.",
  },
  {
    id: "reflection-path",
    title: "A Path to Superintelligence",
    creators: "Reflection AI",
    year: 2025,
    kind: "official",
    locator: "Research agenda, 7 March 2025",
    url: "https://reflection.ai/blog/reflection-a-path-to-superintelligence/",
    note: "Sets out a bet on autonomous coding, reinforcement learning, and transfer to wider computer work. The transfer claim remains a hypothesis without a public frontier artifact.",
  },
  {
    id: "aristotle-report",
    title: "Aristotle: IMO-level Automated Theorem Proving",
    creators: "Harmonic",
    year: 2025,
    kind: "paper",
    locator: "arXiv:2510.01346",
    url: "https://arxiv.org/abs/2510.01346",
    note: "A technical report on Lean proof search, informal reasoning, and a geometry solver. Machine-checked proofs are strong narrow evidence, not general mathematical superintelligence.",
  },
];

export const sourceById = new Map(sources.map((source) => [source.id, source]));
